version: "3.0"

services:
  memcached:
    image: memcached
    restart: always
    expose:
      - "11211"

  yopass:
    image: jhaals/yopass
    restart: always
    ports:
      - "0.0.0.0:1337:1337"
    command: "--memcached=memcached:11211 --port 1337"
